from enum import Enum

class Machine(Enum):
    AVAILABLE_BARS = 8
    BAR_SIZE = 145
    SECURITY_DISTANCE_BARS = 145
    AVAILABLE_SUCTIONS_CUPS = 24
    SUCTION_CUPS_SIZE = 145
    SECURITY_DISTANCE_SUCTION_CUPS = 145
    SUPPORT_AREA = 145 ** 2