from enum import Enum

class Machine(Enum):
    AVAILABLE_BARS = 8
    BAR_SIZE = 145
    AVAILABLE_SUCTIONS_CUPS = 24
    SUCTION_CUPS_SUPPORT_DIMENSION = 145
    SUCTION_CUPS_SUPPORT_AREA = 145 ** 2